### PR TITLE
www.czc.cz

### PR DESCRIPTION
**Pull request by kudlav**
Remove is neccessary, only hiding will not enable page scrolling

### CODE REVIEW

**Comment by Draluy** [comment]
Hi, thx for the MR. This project is no longer mantained. I'm not doing any maintenance anymore, since firefox allows reader mode on most sites, ans ghostery has pushed a similar feature.

**Comment by kudlav** [comment]
Please add this note to the Firefox extension store.

--
Vladan Kudláč

Dne út 20. 12. 2022 16:49 uživatel Draluy ***@***.***> napsal:

**Comment by kudlav** [comment]
And please make this repository archived:
https://docs.github.com/en/repositories/archiving-a-github-repository/archiving-repositories

> You can archive a repository to make it read-only for all users and indicate that it's no longer actively maintained. You can also unarchive repositories that have been archived.

**Comment by Draluy** [comment]
I dont think theres a need to archive the repo, I may want to edit it for myself in the future. I added a note to the extension description to declare iot as unmaintained. There are a couple of hundreds of daily users, so I dont want to remove it completely.

**Comment by kudlav** [comment]
Hi, archived repo is nothing wrong. You can still browse it, it's
searchable but you cannot open issues or pull request. But of course you
can fork it. See in the action:
https://github.com/kudlav/transport_web_components

--
Vladan Kudláč

Dne út 20. 12. 2022 18:51 uživatel Draluy ***@***.***> napsal:

**Pull request closed without merging**
